spring:
  application:
    name: product-administration
  datasource:
    url: jdbc:h2:mem:product_administration;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    openInView: true
    hibernate:
      ddl-auto: create-drop #| create-drop | update | validate | none>
      generate-ddl: true
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.batch_size: 10
        order_updates: true
        batch_versioned_data: true
  sql:
    init:
      mode: always
